Repository DuendeSoftware/products, pull requests merged in 2020-12, with the labels that each got.

#28 License validation
  .gitignore
  src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs
  src/IdentityServer/Configuration/IdentityServerApplicationBuilderExtensions.cs
  src/IdentityServer/Hosting/IdentityServerMiddleware.cs
  src/IdentityServer/Services/Default/DefaultDeviceFlowInteractionService.cs
  src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
  src/IdentityServer/Validation/Default/LicenseValidator.cs
  src/IdentityServer/Validation/Default/TokenRequestValidator.cs
Labels: new feature

#53 Create JTI on each new access token
  src/IdentityServer/Services/Default/DefaultTokenService.cs
  src/Storage/Models/Token.cs
  test/IdentityServer.UnitTests/Common/MockTokenCreationService.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultTokenServiceTests.cs
Labels: bug

#54 add support for ui_locales on end session endpoint
  src/IdentityServer/Endpoints/Results/EndSessionResult.cs
  src/IdentityServer/Logging/Models/EndSessionRequestValidationLog.cs
  src/IdentityServer/Models/Messages/LogoutRequest.cs
  src/IdentityServer/Services/ITokenService.cs
  src/IdentityServer/Validation/Default/EndSessionRequestValidator.cs
  src/IdentityServer/Validation/Models/ValidatedEndSessionRequest.cs
  test/IdentityServer.IntegrationTests/Endpoints/EndSession/EndSessionTests.cs
Labels: enhancement

#48 Enable data protection on persisted grants
  Directory.Build.targets
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs
  src/Storage/Duende.IdentityServer.Storage.csproj
  src/Storage/Stores/Serialization/ClaimConverter.cs
  src/Storage/Stores/Serialization/ClaimsPrincipalConverter.cs
  src/Storage/Stores/Serialization/PersistentGrantSerializer.cs
Labels: new feature

#55 Add abstraction for retrieving the issuer name for the current request
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/Endpoints/DiscoveryEndpoint.cs
  src/IdentityServer/Extensions/IdentityServerToolsExtensions.cs
  src/IdentityServer/IdentityServerTools.cs
  src/IdentityServer/Services/Default/DefaultIssuerNameService.cs
  src/IdentityServer/Services/Default/DefaultTokenService.cs
  src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
  src/IdentityServer/Services/Default/LogoutNotificationService.cs
  src/IdentityServer/Services/IIssuerNameService.cs
  src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
  src/IdentityServer/Validation/Default/JwtRequestValidator.cs
  src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs
  src/IdentityServer/Validation/Default/TokenRequestValidator.cs
  src/IdentityServer/Validation/Default/TokenValidator.cs
  src/IdentityServer/Validation/Models/ValidatedRequest.cs
  test/IdentityServer.UnitTests/Services/Default/KeyManagement/KeyManagerTests.cs
  test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
  test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
  test/IdentityServer.UnitTests/Validation/Setup/TestIssuerNameService.cs
Labels: internal refactoring

#26 iss Response Parameter
  src/IdentityServer/Extensions/AuthorizeResponseExtensions.cs
  src/IdentityServer/ResponseHandling/Default/AuthorizeResponseGenerator.cs
  src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs
  src/IdentityServer/ResponseHandling/Models/AuthorizeResponse.cs
  test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
Labels: new feature

#60 Switching to IdentityModel v5 and remove JSON.NET dependency
  Directory.Build.targets
  clients/src/APIs/ResourceBasedApi/IdentityController.cs
  clients/src/APIs/ResourceBasedApi/Startup.cs
  clients/src/APIs/SimpleApi/IdentityController.cs
  clients/src/APIs/SimpleApi/Startup.cs
  clients/src/ConsoleClientCredentialsFlow/Program.cs
  clients/src/ConsoleClientCredentialsFlowCallingIdentityServerApi/Program.cs
  clients/src/ConsoleClientCredentialsFlowPostBody/Program.cs
  clients/src/ConsoleCustomGrant/Program.cs
  clients/src/ConsoleDeviceFlow/Program.cs
  clients/src/ConsoleEphemeralMtlsClient/Program.cs
  clients/src/ConsoleMTLSClient/Program.cs
  clients/src/ConsoleParameterizedScopeClient/Program.cs
  clients/src/ConsolePrivateKeyJwtClient/Program.cs
  clients/src/ConsoleResourceOwnerFlow/Program.cs
  clients/src/ConsoleResourceOwnerFlowPublic/Program.cs
  clients/src/ConsoleResourceOwnerFlowReference/Program.cs
  clients/src/ConsoleResourceOwnerFlowRefreshToken/Program.cs
  clients/src/Constants/TokenResponseExtensions.cs
  clients/src/MvcCode/Controllers/HomeController.cs
  clients/src/MvcHybridBackChannel/Controllers/HomeController.cs
  clients/src/MvcHybridBackChannel/Controllers/LogoutController.cs
  hosts/AspNetIdentity/Quickstart/Diagnostics/DiagnosticsViewModel.cs
  hosts/EntityFramework/Quickstart/Diagnostics/DiagnosticsViewModel.cs
  hosts/main/Quickstart/Diagnostics/DiagnosticsViewModel.cs
  src/Storage/Stores/Serialization/CustomContractResolver.cs
  test/IdentityServer.IntegrationTests/Clients/ClientAssertionClient.cs
  test/IdentityServer.IntegrationTests/Clients/ClientCredentialsClient.cs
  test/IdentityServer.IntegrationTests/Clients/CustomTokenRequestValidatorClient.cs
  test/IdentityServer.IntegrationTests/Clients/CustomTokenResponseClients.cs
  test/IdentityServer.IntegrationTests/Clients/ExtensionGrantClient.cs
  test/IdentityServer.IntegrationTests/Clients/ResourceOwnerClient.cs
  test/IdentityServer.IntegrationTests/Clients/Setup/ConfirmationSecretValidator.cs
  test/IdentityServer.IntegrationTests/Clients/UserInfoClient.cs
  test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs
  test/IdentityServer.IntegrationTests/Common/JsonElementExtensions.cs
  test/IdentityServer.IntegrationTests/Endpoints/Authorize/JwtRequestAuthorizeTests.cs
  test/IdentityServer.IntegrationTests/Endpoints/DeviceAuthorization/DeviceAuthorizationTests.cs
  test/IdentityServer.IntegrationTests/Endpoints/Discovery/DiscoveryEndpointTests.cs
  test/IdentityServer.IntegrationTests/Endpoints/EndSession/EndSessionTests.cs
  test/IdentityServer.IntegrationTests/Endpoints/Introspection/IntrospectionTests.cs
  test/IdentityServer.IntegrationTests/Endpoints/Token/TokenEndpointTests.cs
  test/IdentityServer.IntegrationTests/Extensibility/CustomProfileServiceTests.cs
Labels: internal refactoring

#64 Optimize claims serialization for persisted grants
  src/Storage/Stores/Serialization/ClaimConverter.cs
  src/Storage/Stores/Serialization/ClaimsPrincipalConverter.cs
  src/Storage/Stores/Serialization/PersistentGrantSerializer.cs
Labels: internal refactoring
