Repository DuendeSoftware/products, pull requests merged in 2021-09, with the labels that each got.

#387 use singlular targetframework tag in project files
  hosts/AspNetIdentity/Host.AspNetIdentity.csproj
  hosts/EntityFramework/Host.EntityFramework.csproj
  hosts/main/Host.Main.csproj
  migrations/AspNetIdentityDb/AspNetIdentityDb.csproj
  migrations/IdentityServerDb/IdentityServerDb.csproj
  src/AspNetIdentity/Duende.IdentityServer.AspNetIdentity.csproj
  src/EntityFramework.Storage/Duende.IdentityServer.EntityFramework.Storage.csproj
  src/EntityFramework/Duende.IdentityServer.EntityFramework.csproj
  src/Storage/Duende.IdentityServer.Storage.csproj
  test/EntityFramework.Storage.IntegrationTests/EntityFramework.Storage.IntegrationTests.csproj
  test/EntityFramework.Storage.UnitTests/EntityFramework.Storage.UnitTests.csproj
  test/EntityFramework.Tests/EntityFramework.Tests.csproj
  test/IdentityServer.IntegrationTests/IdentityServer.IntegrationTests.csproj
  test/IdentityServer.UnitTests/IdentityServer.UnitTests.csproj
Labels: internal

#388 [EF] Optimize client query to use a single DB round trip
  src/EntityFramework.Storage/Stores/ClientStore.cs
  test/EntityFramework.Storage.IntegrationTests/IntegrationTest.cs
Labels: enhancement

#389 Replace Uri.TryCreate with Uri.IsWellformedUriString
  src/IdentityServer/Extensions/ResourceExtensions.cs
  src/IdentityServer/Services/Default/OidcReturnUrlParser.cs
  src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
  src/IdentityServer/Validation/Default/DefaultClientConfigurationValidator.cs
  test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Invalid.cs
Labels: enhancement

#403 [EF] Change DbContext constructors to support pooling
  src/EntityFramework.Storage/Configuration/ServiceCollectionExtensions.cs
  src/EntityFramework.Storage/DbContexts/ConfigurationDbContext.cs
  src/EntityFramework.Storage/DbContexts/PersistedGrantDbContext.cs
  src/EntityFramework.Storage/Options/ConfigurationStoreOptions.cs
  src/EntityFramework.Storage/Options/OperationalStoreOptions.cs
  test/EntityFramework.Storage.IntegrationTests/DatabaseProviderBuilder.cs
  test/EntityFramework.Storage.IntegrationTests/DatabaseProviderFixture.cs
  test/EntityFramework.Storage.IntegrationTests/DbContexts/ClientDbContextTests.cs
  test/EntityFramework.Storage.IntegrationTests/IntegrationTest.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/ClientStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/DeviceFlowStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/IdentityProviderStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/PersistedGrantStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/ResourceStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/TokenCleanup/TokenCleanupTests.cs
  test/EntityFramework.Tests/DatabaseProviderBuilder.cs
  test/EntityFramework.Tests/DatabaseProviderFixture.cs
  test/EntityFramework.Tests/IntegrationTest.cs
  test/EntityFramework.Tests/Services/CorsPolicyServiceTests.cs
Labels: enhancement

#406 Ignore EF warning about split vs non-split queries
  hosts/EntityFramework/Startup.cs
Labels: internal

#404 Encode persisted grant handles to avoid collation issues
  src/IdentityServer/Stores/Default/DefaultGrantStore.cs
  test/IdentityServer.UnitTests/Stores/Default/DefaultPersistedGrantStoreTests.cs
Labels: enhancement

#407 add test for v5 persisted grant handle format
  test/IdentityServer.UnitTests/Services/Default/DefaultRefreshTokenServiceTests.cs
Labels: internal

#409 Suppress EF warning about split query behavior
  hosts/EntityFramework/Startup.cs
  src/EntityFramework.Storage/DbContexts/ConfigurationDbContext.cs
Labels: internal

#410 Enhancements to front channel logout iframes
  src/IdentityServer/Endpoints/Results/EndSessionCallbackResult.cs
  test/IdentityServer.UnitTests/Endpoints/Results/EndSessionCallbackResultTests.cs
Labels: enhancement

#413 add razor dynamic compilation
  hosts/AspNetIdentity/Host.AspNetIdentity.csproj
  hosts/AspNetIdentity/Startup.cs
  hosts/EntityFramework/Host.EntityFramework.csproj
  hosts/EntityFramework/Startup.cs
  hosts/main/Program.cs
Labels: internal

#416 Fix bug when storing session id in refresh token
  src/IdentityServer/Services/Default/DefaultRefreshTokenService.cs
  src/Storage/Models/RefreshToken.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultPersistedGrantServiceTests.cs
  test/IdentityServer.UnitTests/Stores/Default/DefaultPersistedGrantStoreTests.cs
Labels: bug

#420 Change the cache key separator to use more redis friendly value
  src/IdentityServer/Hosting/DynamicProviders/Store/CachingIdentityProviderStore.cs
  src/IdentityServer/Services/Default/DefaultCache.cs
  src/IdentityServer/Services/Default/DefaultReplayCache.cs
Labels: enhancement

#419 Fix bug in cache removal for DistributedCacheAuthorizationParametersMessageStore
  src/IdentityServer/Stores/Default/DistributedCacheAuthorizationParametersMessageStore.cs
  test/IdentityServer.UnitTests/Common/MockDistributedCache.cs
  test/IdentityServer.UnitTests/Stores/Default/DistributedCacheAuthorizationParametersMessageStoreTests.cs
Labels: bug

#418 Remove custom serialization handling for AuthenticationProperties
  src/IdentityServer/Infrastructure/DistributedCacheStateDataFormatter.cs
Labels: internal

#424 rename internal static field to match conventions
  src/Storage/Stores/Serialization/PersistentGrantSerializer.cs
Labels: internal

#405 Add cancellation token support at boundaries
  hosts/EntityFramework/TestOperationalStoreNotification.cs
  src/EntityFramework.Storage/Interfaces/IPersistedGrantDbContext.cs
  src/EntityFramework.Storage/Stores/ClientStore.cs
  src/EntityFramework.Storage/Stores/DeviceFlowStore.cs
  src/EntityFramework.Storage/Stores/IdentityProviderStore.cs
  src/EntityFramework.Storage/Stores/PersistedGrantStore.cs
  src/EntityFramework.Storage/Stores/ResourceStore.cs
  src/EntityFramework.Storage/Stores/SigningKeyStore.cs
  src/EntityFramework.Storage/TokenCleanup/IOperationalStoreNotification.cs
  src/EntityFramework.Storage/TokenCleanup/TokenCleanupService.cs
  src/EntityFramework/Services/CorsPolicyService.cs
  src/EntityFramework/TokenCleanupHost.cs
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/Services/Default/BackChannelLogoutHttpClient.cs
  src/IdentityServer/Services/Default/DefaultHttpContextCancellationTokenICancellationTokenProvider.cs
  src/IdentityServer/Services/Default/DefaultJwtRequestUriHttpClient.cs
  src/Storage/Services/ICancellationTokenProvider.cs
  src/Storage/Services/NoneCancellationTokenProvider.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/ClientStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/DeviceFlowStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/IdentityProviderStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/PersistedGrantStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/ResourceStoreTests.cs
  test/EntityFramework.Tests/Services/CorsPolicyServiceTests.cs
  test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Labels: enhancement

#414 Reduce usage of HttpContext extension methods
  hosts/AspNetIdentity/Pages/Extensions.cs
  hosts/EntityFramework/Pages/Extensions.cs
  hosts/main/Pages/Consent/InputModel.cs
  hosts/main/Pages/Device/InputModel.cs
  hosts/main/Pages/Extensions.cs
  hosts/main/Pages/SecurityHeadersAttribute.cs
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/Endpoints/DeviceAuthorizationEndpoint.cs
  src/IdentityServer/Endpoints/DiscoveryEndpoint.cs
  src/IdentityServer/Endpoints/Results/AuthorizeResult.cs
  src/IdentityServer/Endpoints/Results/ConsentPageResult.cs
  src/IdentityServer/Endpoints/Results/CustomRedirectResult.cs
  src/IdentityServer/Endpoints/Results/EndSessionResult.cs
  src/IdentityServer/Endpoints/Results/LoginPageResult.cs
  src/IdentityServer/Extensions/HttpContextAuthenticationExtensions.cs
  src/IdentityServer/Extensions/HttpContextExtensions.cs
  src/IdentityServer/Extensions/HttpResponseExtensions.cs
  src/IdentityServer/Extensions/ServerUrlExtensions.cs
  src/IdentityServer/Hosting/BaseUrlMiddleware.cs
  src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationOptions.cs
  src/IdentityServer/Hosting/DynamicProviders/Oidc/OidcConfigureOptions.cs
  src/IdentityServer/Hosting/DynamicProviders/Store/CachingIdentityProviderStore.cs
  src/IdentityServer/Infrastructure/MessageCookie.cs
  src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs
  src/IdentityServer/Services/Default/DefaultIssuerNameService.cs
  src/IdentityServer/Services/Default/DefaultJwtRequestUriHttpClient.cs
  src/IdentityServer/Services/Default/DefaultServerUrls.cs
  src/IdentityServer/Services/Default/DefaultUserSession.cs
  src/IdentityServer/Services/Default/OidcReturnUrlParser.cs
  src/IdentityServer/Services/IIssuerNameService.cs
  src/IdentityServer/Services/IServerUrls.cs
  src/IdentityServer/Validation/Default/EndSessionRequestValidator.cs
  src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs
  src/Storage/Stores/IIdentityProviderStore.cs
  test/IdentityServer.UnitTests/Common/MockHttpContextAccessor.cs
  test/IdentityServer.UnitTests/Common/MockServerUrls.cs
  test/IdentityServer.UnitTests/Common/TestExtensions.cs
  test/IdentityServer.UnitTests/Endpoints/Results/AuthorizeResultTests.cs
  test/IdentityServer.UnitTests/Endpoints/Results/CheckSessionResultTests.cs
  test/IdentityServer.UnitTests/Endpoints/Results/EndSessionCallbackResultTests.cs
  test/IdentityServer.UnitTests/Endpoints/Results/EndSessionResultTests.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultIdentityServerInteractionServiceTests.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultUserSessionTests.cs
  test/IdentityServer.UnitTests/Services/Default/OidcReturnUrlParserTests.cs
  test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
Labels: enhancement

#415 Add IdentityProvider validator
  hosts/main/Startup.cs
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/Events/Infrastructure/EventIds.cs
  src/IdentityServer/Events/InvalidClientConfiguration.cs
  src/IdentityServer/Events/InvalidIdentityProviderConfiguration.cs
  src/IdentityServer/Hosting/DynamicProviders/Oidc/IdentityServerBuilderOidcExtensions.cs
  src/IdentityServer/Hosting/DynamicProviders/Store/ValidatingIdentityProviderStore.cs
  src/IdentityServer/Validation/Contexts/IdentityProviderConfigurationValidationContext.cs
  src/IdentityServer/Validation/Default/DefaultIdentityProviderConfigurationValidator.cs
  src/IdentityServer/Validation/IIdentityProviderConfigurationValidator.cs
  test/IdentityServer.UnitTests/Validation/IdentityProviderConfigurationValidation.cs
Labels: enhancement

#423 Add finer grained IdentityServerBuilderExtensions for registering cookie authentication services
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/Hosting/IdentityServerAuthenticationService.cs
Labels: enhancement

#425 Change lifetime of nested options in DI to be more multi-tenant friendly
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
Labels: enhancement

#421 Add feature to the default cache to prevent concurrent reloading of the cache
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/CachingOptions.cs
  src/IdentityServer/Extensions/ICacheExtensions.cs
  src/IdentityServer/Hosting/DynamicProviders/Store/CachingIdentityProviderStore.cs
  src/IdentityServer/Infrastructure/ConcurrencyLock/DefaultConcurrencyLock.cs
  src/IdentityServer/Infrastructure/ConcurrencyLock/IConcurrencyLock.cs
  src/IdentityServer/Infrastructure/ConcurrencyLock/NopConcurrencyLock.cs
  src/IdentityServer/Services/Default/DefaultCache.cs
  src/IdentityServer/Services/Default/KeyManagement/DefaultKeyLock.cs
  src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
  src/IdentityServer/Services/ICache.cs
  src/IdentityServer/Stores/Caching/CachingClientStore.cs
  src/IdentityServer/Stores/Caching/CachingCorsPolicyService.cs
  src/IdentityServer/Stores/Caching/CachingResourceStore.cs
  test/IdentityServer.IntegrationTests/Hosting/DynamicProvidersTests.cs
  test/IdentityServer.UnitTests/Services/Default/KeyManagement/KeyManagerTests.cs
Labels: enhancement

#431 Change cache design for resource store cache
  src/IdentityServer/Hosting/DynamicProviders/Store/CachingIdentityProviderStore.cs
  src/IdentityServer/Stores/Caching/CachingResourceStore.cs
  test/IdentityServer.UnitTests/Common/MockCache.cs
  test/IdentityServer.UnitTests/Stores/Default/CachingResourceStoreTests.cs
Labels: enhancement

#436 add simple perf test host app
  perf/IdentityServer.PerfTests/BenchmarkDotNet.Artifacts/results/IdentityServer.PerfTests.Services.DefaultTokenServiceTest-report-github.md
  perf/IdentityServer.PerfTests/BenchmarkDotNet.Artifacts/results/IdentityServer.PerfTests.Services.DefaultTokenServiceTest-report.csv
  perf/IdentityServer.PerfTests/BenchmarkDotNet.Artifacts/results/IdentityServer.PerfTests.Services.DefaultTokenServiceTest-report.html
  perf/IdentityServer.PerfTests/IdentityServer.PerfTests.csproj
  perf/IdentityServer.PerfTests/Infrastructure/DebugLoggerProvider.cs
  perf/IdentityServer.PerfTests/Infrastructure/IdentityServerContainer.cs
  perf/IdentityServer.PerfTests/Infrastructure/InMemoryIdentityServerContainer.cs
  perf/IdentityServer.PerfTests/Infrastructure/TestBase.cs
  perf/IdentityServer.PerfTests/Program.cs
  perf/IdentityServer.PerfTests/Services/DefaultTokenServiceTest.cs
  perf/IdentityServer.PerfTests/client.cer
  perf/IdentityServer.PerfTests/client.pfx
  perf/PerfTests.sln
Labels: internal
