Repository DuendeSoftware/products, pull requests merged in 2021-01, with the labels that each got.

#68 Add option to specify whether s_hash should be emitted.
  src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs
  src/IdentityServer/ResponseHandling/Default/AuthorizeResponseGenerator.cs
  test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs
  test/IdentityServer.IntegrationTests/Conformance/Basic/CodeFlowTests.cs
Labels: enhancement

#78 typos in code comments
  src/IdentityServer/Services/IPersistedGrantService.cs
  src/Storage/Models/SerializedKey.cs
Labels: bug

#85 Add NuGet package signing
  .config/dotnet-tools.json
  .github/workflows/ci.yml
  build.cmd
  build.ps1
  build.sh
  build/Program.cs
Labels: internal

#87 Fix misuse DateTimeOffset and UTC in KeyManagement
  src/IdentityServer/Extensions/KeyManagementExtensions.cs
  src/IdentityServer/Services/Default/DefaultRefreshTokenService.cs
  src/IdentityServer/Services/Default/KeyManagement/InMemoryKeyStoreCache.cs
  src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
  test/IdentityServer.UnitTests/Services/Default/KeyManagement/InMemoryKeyStoreCacheTests.cs
  test/IdentityServer.UnitTests/Services/Default/KeyManagement/KeyManagerTests.cs
Labels: bug
