Repository DuendeSoftware/products, pull requests merged in 2021-12, with the labels that each got.

#553 CIBA unit tests
  clients/src/ConsoleCibaClient/Program.cs
  clients/src/Constants/Constants.csproj
  hosts/AspNetIdentity/Pages/Ciba/Consent.cshtml.cs
  hosts/AspNetIdentity/Pages/Ciba/Index.cshtml.cs
  hosts/EntityFramework/Pages/Ciba/Consent.cshtml.cs
  hosts/EntityFramework/Pages/Ciba/Index.cshtml.cs
  hosts/main/Pages/Ciba/Consent.cshtml.cs
  hosts/main/Pages/Ciba/Index.cshtml.cs
  src/IdentityServer/Endpoints/BackchannelAuthenticationEndpoint.cs
  src/IdentityServer/Models/BackchannelUserLoginRequest.cs
  src/IdentityServer/ResponseHandling/Default/BackchannelAuthenticationResponseGenerator.cs
  src/IdentityServer/Services/Default/DefaultBackchannelAuthenticationInteractionService.cs
  src/IdentityServer/Services/IBackchannelAuthenticationInteractionService.cs
  src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs
  test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs
  test/IdentityServer.IntegrationTests/Common/MockCibaUserNotificationService.cs
  test/IdentityServer.IntegrationTests/Common/MockCibaUserValidator.cs
  test/IdentityServer.IntegrationTests/Common/MockClock.cs
  test/IdentityServer.IntegrationTests/Common/MockResourceValidator.cs
  test/IdentityServer.IntegrationTests/Endpoints/Ciba/CibaTests.cs
  test/IdentityServer.IntegrationTests/Endpoints/Token/CibaTokenEndpointTests.cs
Labels: internal

#566 Cleanup on the external callback quickstart UI
  hosts/AspNetIdentity/Pages/Account/Login/Index.cshtml.cs
  hosts/AspNetIdentity/Pages/Account/Logout/Index.cshtml.cs
  hosts/AspNetIdentity/Pages/Consent/InputModel.cs
  hosts/AspNetIdentity/Pages/Device/InputModel.cs
  hosts/AspNetIdentity/Pages/Extensions.cs
  hosts/AspNetIdentity/Pages/ExternalLogin/Callback.cshtml.cs
  hosts/AspNetIdentity/Pages/SecurityHeadersAttribute.cs
  hosts/EntityFramework/Pages/Consent/InputModel.cs
  hosts/EntityFramework/Pages/Device/InputModel.cs
  hosts/EntityFramework/Pages/Extensions.cs
  hosts/EntityFramework/Pages/ExternalLogin/Callback.cshtml.cs
  hosts/EntityFramework/Pages/SecurityHeadersAttribute.cs
  hosts/main/Pages/ExternalLogin/Callback.cshtml.cs
Labels: internal

#556 Add support to set subject for ciba login request outside of browser session
  clients/src/ConsoleCibaClient/Program.cs
  hosts/AspNetIdentity/Pages/Ciba/Consent.cshtml.cs
  hosts/AspNetIdentity/Pages/Ciba/Index.cshtml.cs
  hosts/EntityFramework/Pages/Ciba/Consent.cshtml.cs
  hosts/EntityFramework/Pages/Ciba/Index.cshtml.cs
  hosts/main/Pages/Ciba/Consent.cshtml.cs
  hosts/main/Pages/Ciba/Index.cshtml.cs
  src/IdentityServer/Services/Default/DefaultBackchannelAuthenticationInteractionService.cs
  src/IdentityServer/Services/IBackchannelAuthenticationInteractionService.cs
  src/IdentityServer/Stores/Default/DefaultBackChannelAuthenticationRequestStore.cs
  src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestIdValidator.cs
  src/Storage/Models/BackChannelAuthenticationRequest.cs
  src/Storage/Stores/IBackChannelAuthenticationRequestStore.cs
  test/EntityFramework.Tests/EntityFramework.Tests.csproj
  test/IdentityServer.IntegrationTests/Endpoints/Token/CibaTokenEndpointTests.cs
  test/IdentityServer.UnitTests/Common/MockBackChannelAuthenticationRequestStore.cs
  test/IdentityServer.UnitTests/Common/MockSystemClock.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultBackchannelAuthenticationInteractionServiceTests.cs
Labels: internal

#578 Add global authorization filter to pages
  hosts/AspNetIdentity/Pages/Account/Logout/Index.cshtml.cs
  hosts/AspNetIdentity/Pages/Ciba/Consent.cshtml.cs
  hosts/AspNetIdentity/Pages/Ciba/Index.cshtml.cs
  hosts/AspNetIdentity/Pages/ExternalLogin/Callback.cshtml.cs
  hosts/AspNetIdentity/Pages/ExternalLogin/Challenge.cshtml.cs
  hosts/AspNetIdentity/Pages/Home/Error/Index.cshtml.cs
  hosts/AspNetIdentity/Pages/Redirect/Index.cshtml.cs
  hosts/AspNetIdentity/Startup.cs
  hosts/EntityFramework/Pages/Account/Logout/Index.cshtml.cs
  hosts/EntityFramework/Pages/Account/Logout/LoggedOut.cshtml.cs
  hosts/EntityFramework/Pages/Ciba/Consent.cshtml.cs
  hosts/EntityFramework/Pages/Ciba/Index.cshtml.cs
  hosts/EntityFramework/Pages/ExternalLogin/Callback.cshtml.cs
  hosts/EntityFramework/Pages/ExternalLogin/Challenge.cshtml.cs
  hosts/EntityFramework/Pages/Home/Error/Index.cshtml.cs
  hosts/EntityFramework/Pages/Redirect/Index.cshtml.cs
  hosts/EntityFramework/Startup.cs
  hosts/main/Pages/Account/Logout/Index.cshtml.cs
  hosts/main/Pages/Account/Logout/LoggedOut.cshtml.cs
  hosts/main/Pages/Ciba/Index.cshtml.cs
  hosts/main/Pages/ExternalLogin/Callback.cshtml.cs
  hosts/main/Pages/ExternalLogin/Challenge.cshtml.cs
  hosts/main/Pages/Home/Error/Index.cshtml.cs
  hosts/main/Pages/Redirect/Index.cshtml.cs
  hosts/main/Startup.cs
Labels: internal

#583 Add warning when using dynamic provider outside http request
  src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicAuthenticationSchemeProvider.cs
Labels: enhancement

#589 Update community edition license validation rules for v6.0
  src/IdentityServer/Validation/Default/License.cs
  test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
Labels: enhancement

#605 Add idp claim to uer's claims when using external idp
  hosts/AspNetIdentity/Pages/ExternalLogin/Callback.cshtml.cs
Labels: internal

#600 Add BFF edition license logic
  src/IdentityServer/Validation/Default/License.cs
  src/IdentityServer/Validation/Default/LicenseValidator.cs
  test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
Labels: internal

#601 EF: shorten client redirect URIs
  migrations/IdentityServerDb/Migrations/ConfigurationDb.sql
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20211221171528_Configuration.Designer.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20211221171528_Configuration.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/ConfigurationDbContextModelSnapshot.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb.sql
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20211221171522_Grants.Designer.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20211221171522_Grants.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/PersistedGrantDbContextModelSnapshot.cs
  src/EntityFramework.Storage/Extensions/ModelBuilderExtensions.cs
Labels: internal

#611 Rename helper that adds ciba user notification service
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
  src/IdentityServer/Endpoints/BackchannelAuthenticationEndpoint.cs
Labels: internal

#614 Add simple pages for config management to EF quickstart
  Duende.IdentityServer.sln
  hosts/AspNetIdentity/Pages/Account/AccessDenied.cshtml
  hosts/AspNetIdentity/Pages/Account/AccessDenied.cshtml.cs
  hosts/EntityFramework/HostingExtensions.cs
  hosts/EntityFramework/IdentityServerExtensions.cs
  hosts/EntityFramework/Pages/Account/AccessDenied.cshtml
  hosts/EntityFramework/Pages/Account/AccessDenied.cshtml.cs
  hosts/EntityFramework/Pages/Admin/ApiScopes/ApiScopeRepository.cs
  hosts/EntityFramework/Pages/Admin/ApiScopes/Edit.cshtml
  hosts/EntityFramework/Pages/Admin/ApiScopes/Edit.cshtml.cs
  hosts/EntityFramework/Pages/Admin/ApiScopes/Index.cshtml
  hosts/EntityFramework/Pages/Admin/ApiScopes/Index.cshtml.cs
  hosts/EntityFramework/Pages/Admin/ApiScopes/New.cshtml
  hosts/EntityFramework/Pages/Admin/ApiScopes/New.cshtml.cs
  hosts/EntityFramework/Pages/Admin/Clients/ClientRepository.cs
  hosts/EntityFramework/Pages/Admin/Clients/Edit.cshtml
  hosts/EntityFramework/Pages/Admin/Clients/Edit.cshtml.cs
  hosts/EntityFramework/Pages/Admin/Clients/Index.cshtml
  hosts/EntityFramework/Pages/Admin/Clients/Index.cshtml.cs
  hosts/EntityFramework/Pages/Admin/Clients/New.cshtml
  hosts/EntityFramework/Pages/Admin/Clients/New.cshtml.cs
  hosts/EntityFramework/Pages/Admin/IdentityScopes/Edit.cshtml
  hosts/EntityFramework/Pages/Admin/IdentityScopes/Edit.cshtml.cs
  hosts/EntityFramework/Pages/Admin/IdentityScopes/IdentityScopeRepository.cs
  hosts/EntityFramework/Pages/Admin/IdentityScopes/Index.cshtml
  hosts/EntityFramework/Pages/Admin/IdentityScopes/Index.cshtml.cs
  hosts/EntityFramework/Pages/Admin/IdentityScopes/New.cshtml
  hosts/EntityFramework/Pages/Admin/IdentityScopes/New.cshtml.cs
  hosts/EntityFramework/Pages/Admin/Index.cshtml
  hosts/EntityFramework/Pages/Admin/Index.cshtml.cs
  hosts/EntityFramework/Pages/Index.cshtml
  hosts/EntityFramework/Pages/TestUsers.cs
  hosts/main/Pages/Account/AccessDenied.cshtml
  hosts/main/Pages/Account/AccessDenied.cshtml.cs
  hosts/main/Pages/TestUsers.cs
  hosts/main/wwwroot/css/site.css
  hosts/main/wwwroot/css/site.min.css
  hosts/main/wwwroot/css/site.scss
Labels: enhancement

#619 Fix PostLogout check in AppAuth redirect validator
  src/IdentityServer/Validation/Default/StrictRedirectUriValidatorAppAuth.cs
Labels: bug

#620 Sync css across sample hosts
  hosts/AspNetIdentity/wwwroot/css/site.css
  hosts/AspNetIdentity/wwwroot/css/site.scss
  hosts/EntityFramework/wwwroot/css/site.css
  hosts/EntityFramework/wwwroot/css/site.scss
Labels: internal

#621 Bug in admin pages using wrong entity
  hosts/EntityFramework/Pages/Admin/ApiScopes/ApiScopeRepository.cs
Labels: internal

#622 remove unnecessary decorator in AddIdentityProviderStore
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
  test/EntityFramework.Tests/DI/DITests.cs
Labels: bug, internal

#625 Adjust ASP.NET Identity integration to use EmailClaimType option
  src/AspNetIdentity/IdentityServerBuilderExtensions.cs
  src/AspNetIdentity/UserClaimsFactory.cs
Labels: internal
