Repository DuendeSoftware/products, pull requests merged in 2022-06, with the labels that each got.

#908 Lock down GH actions
  .github/workflows/ci.yml
  .github/workflows/lock.yml
Labels: build

#922 Introduce option to emit/suppress iss parameter
  src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs
  src/IdentityServer/Endpoints/Results/AuthorizeResult.cs
  src/IdentityServer/Extensions/AuthorizeResponseExtensions.cs
Labels: enhancement

#939 fix logger type for CIBA consent page
  hosts/AspNetIdentity/Pages/Ciba/Consent.cshtml.cs
  hosts/EntityFramework/Pages/Ciba/Consent.cshtml.cs
  hosts/main/Pages/Ciba/Consent.cshtml.cs
Labels: bug
