Repository DuendeSoftware/products, pull requests merged in 2022-03, with the labels that each got.

#793 add identity column to persisted grants table
  migrations/IdentityServerDb/Migrations/ConfigurationDb.sql
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20220309202515_Configuration.Designer.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20220309202515_Configuration.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb.sql
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20220309202509_Grants.Designer.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20220309202509_Grants.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/PersistedGrantDbContextModelSnapshot.cs
  src/EntityFramework.Storage/Entities/PersistedGrant.cs
  src/EntityFramework.Storage/Extensions/ModelBuilderExtensions.cs
Labels: enhancement

#812 Update Bullseye
  Directory.Build.targets
  build/Program.cs
Labels: internal

#800 Improve grammar and code readability
  src/EntityFramework.Storage/Entities/IdentityProvider.cs
  src/EntityFramework.Storage/Stores/ResourceStore.cs
  src/EntityFramework.Storage/Stores/ServerSideSessionStore.cs
  src/EntityFramework/TokenCleanupHost.cs
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/InMemory.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/AuthenticationOptions.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/CspOptions.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/DynamicProviderOptions.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/UserInteractionOptions.cs
  src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs
  src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationContext.cs
  src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicAuthenticationSchemeProvider.cs
  src/IdentityServer/Models/Contexts/IsActiveContext.cs
  src/IdentityServer/Models/Contexts/LogoutNotificationContext.cs
  src/IdentityServer/Models/Messages/LogoutRequest.cs
  src/IdentityServer/ResponseHandling/Default/DeviceAuthorizationResponseGenerator.cs
  src/IdentityServer/ResponseHandling/Default/UserInfoResponseGenerator.cs
  src/IdentityServer/Services/Default/KeyManagement/InMemoryKeyStoreCache.cs
  src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
  src/IdentityServer/Services/ISessionManagementService.cs
  src/IdentityServer/Stores/Default/DefaultGrantStore.cs
  src/IdentityServer/Stores/InMemory/InMemoryServerSideSessionStore.cs
  src/IdentityServer/Validation/Default/HashedSharedSecretValidator.cs
  src/IdentityServer/Validation/Default/License.cs
  src/IdentityServer/Validation/Default/LicenseValidator.cs
  src/IdentityServer/Validation/Models/ValidatedAuthorizeRequest.cs
  src/IdentityServer/Validation/Models/ValidationResult.cs
  src/Storage/Models/RefreshToken.cs
  src/Storage/Stores/SessionFilter.cs
  src/Storage/Stores/SessionQuery.cs
  src/Tracing/Tracing.cs
Labels: internal

#802 update session id and description for user interaction in device flow
  clients/src/ConsoleDeviceFlow/Program.cs
  src/EntityFramework.Storage/Stores/DeviceFlowStore.cs
Labels: bug

#801 [EF] add back overloaded ctor for accepting store options for DbContexts
  src/EntityFramework.Storage/DbContexts/ConfigurationDbContext.cs
  src/EntityFramework.Storage/DbContexts/PersistedGrantDbContext.cs
Labels: enhancement

#809 [EF] Add indices to new server-side session tables
  migrations/IdentityServerDb/Migrations/ConfigurationDb.sql
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20220314164929_Configuration.Designer.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20220314164929_Configuration.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb.sql
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20220314164923_Grants.Designer.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20220314164923_Grants.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/PersistedGrantDbContextModelSnapshot.cs
  src/EntityFramework.Storage/Extensions/ModelBuilderExtensions.cs
  src/Storage/Models/QueryResult.cs
Labels: internal

#834 Reduce noise from key manager logging
  src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
Labels: internal

#811 Adopt different logging approach for redistribution license
  src/IdentityServer/Configuration/IdentityServerApplicationBuilderExtensions.cs
  src/IdentityServer/Validation/Default/License.cs
  src/IdentityServer/Validation/Default/LicenseValidator.cs
  test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
Labels: internal

#820 Server-side session management features
  clients/src/MvcHybridBackChannel/Startup.cs
  hosts/EntityFramework/IdentityServerExtensions.cs
  hosts/main/IdentityServerExtensions.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb.sql
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20220323143742_Configuration.Designer.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20220323143742_Configuration.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/ConfigurationDbContextModelSnapshot.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb.sql
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20220323143735_Grants.Designer.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20220323143735_Grants.cs
  src/EntityFramework.Storage/Entities/Client.cs
  src/EntityFramework.Storage/Extensions/DbContextExtensions.cs
  src/EntityFramework.Storage/Options/OperationalStoreOptions.cs
  src/EntityFramework.Storage/Stores/ServerSideSessionStore.cs
  src/EntityFramework.Storage/TokenCleanup/IOperationalStoreNotification.cs
  src/EntityFramework.Storage/TokenCleanup/TokenCleanupService.cs
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/SessionManagement.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/AuthenticationOptions.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/ServerSideSessionOptions.cs
  src/IdentityServer/Configuration/DependencyInjection/PostConfigureApplicationCookieTicketStore.cs
  src/IdentityServer/Extensions/AuthenticationTicketExtensions.cs
  src/IdentityServer/Extensions/IUserSessionExtensions.cs
  src/IdentityServer/Hosting/IdentityServerMiddleware.cs
  src/IdentityServer/Hosting/ServerSideSessionCleanupHost.cs
  src/IdentityServer/IdentityServerConstants.cs
  src/IdentityServer/Models/Contexts/LogoutNotificationContext.cs
  src/IdentityServer/Services/Default/DefaultBackChannelLogoutService.cs
  src/IdentityServer/Services/Default/DefaultSessionCoordinationService.cs
  src/IdentityServer/Services/Default/DefaultSessionManagementService.cs
  src/IdentityServer/Services/Default/LogoutNotificationService.cs
  src/IdentityServer/Services/Default/ServerSideSessionRefreshTokenService.cs
  src/IdentityServer/Services/Default/ServerSideTicketStore.cs
  src/IdentityServer/Services/ILogoutNotificationService.cs
  src/IdentityServer/Services/IServerSideTicketService.cs
  src/IdentityServer/Services/ISessionCoordinationService.cs
  src/IdentityServer/Services/ISessionManagementService.cs
  src/IdentityServer/Stores/InMemory/InMemoryServerSideSessionStore.cs
  src/IdentityServer/Validation/Default/TokenValidator.cs
  src/Storage/Models/Client.cs
  src/Storage/Stores/IServerSideSessionStore.cs
  test/IdentityServer.IntegrationTests/Hosting/ServerSideSessionTests.cs
  test/IdentityServer.UnitTests/Common/StubSessionCoordinationService.cs
  test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Labels: new feature

#835 Make invalid client behavior consistent in token validator
  src/IdentityServer/Validation/Default/TokenValidator.cs
Labels: bug

#836 [EF] Make persisted grant PK long (from int)
  migrations/IdentityServerDb/Migrations/ConfigurationDb.sql
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20220324152912_Configuration.Designer.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20220324152912_Configuration.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb.sql
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20220324152905_Grants.Designer.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20220324152905_Grants.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/PersistedGrantDbContextModelSnapshot.cs
  src/EntityFramework.Storage/Entities/PersistedGrant.cs
Labels: internal
