Repository DuendeSoftware/products, pull requests merged in 2022-01, with the labels that each got.

#632 better handling of when user profile is not loaded for x509cert2 usage
  src/IdentityServer/Services/Default/KeyManagement/X509KeyContainer.cs
Labels: bug

#633 When creating token payload, ignore custom claims used for token validation (e.g. aud, iat, etc)
  src/IdentityServer/Extensions/TokenExtensions.cs
  test/IdentityServer.UnitTests/Validation/IdentityTokenValidation.cs
Labels: bug

#628 Add CIBA feature flag and validation check to license
  src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs
  src/IdentityServer/Validation/Default/License.cs
  src/IdentityServer/Validation/Default/LicenseValidator.cs
  src/IdentityServer/Validation/Default/TokenRequestValidator.cs
  test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
Labels: internal

#634 Merge v5.2.4 bug fixes forward
  src/IdentityServer/Extensions/TokenExtensions.cs
  src/IdentityServer/Services/Default/KeyManagement/X509KeyContainer.cs
  test/IdentityServer.UnitTests/Validation/IdentityTokenValidation.cs
Labels: internal

#635 Update AutoMapper to v11
  Directory.Build.targets
  test/EntityFramework.Storage.UnitTests/Mappers/ApiResourceMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/ClientMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/IdentityProviderMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/IdentityResourcesMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/PersistedGrantMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/ScopeMappersTests.cs
Labels: internal

#646 Fix OnConfiguring exception from EF when DbContext pooling is enabled
  src/EntityFramework.Storage/DbContexts/ConfigurationDbContext.cs
Labels: bug

#670 Allow empty secret when validating OIDC IDP config
  src/IdentityServer/Validation/Default/DefaultIdentityProviderConfigurationValidator.cs
  test/IdentityServer.UnitTests/Validation/IdentityProviderConfigurationValidation.cs
Labels: bug

#685 Optimize trace/debug logging
  src/IdentityServer/Logging/ILoggerExtensions.cs
Labels: internal

#663 Use the built-in CSPRNG GetInt32
  src/IdentityServer/Services/Default/NumericUserCodeGenerator.cs
Labels: enhancement

#688 Cleanup on the UI quickstart code based on template feedback
  hosts/AspNetIdentity/Pages/Account/Login/Index.cshtml.cs
  hosts/EntityFramework/Pages/Account/Login/Index.cshtml.cs
  hosts/main/Pages/Account/Login/Index.cshtml.cs
Labels: internal

#690 update .NET version in console CC sample
  clients/src/ConsoleClientCredentialsFlow/ConsoleClientCredentialsFlow.csproj
Labels: internal

#692 merge forward bug fix for loading api resources by scope
  src/IdentityServer/Stores/Caching/CachingResourceStore.cs
  test/IdentityServer.UnitTests/Stores/Default/CachingResourceStoreTests.cs
Labels: internal

#697 Add CIBA grant type to discovery when endpoint is enabled.
  src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs
Labels: bug
