Repository DuendeSoftware/products, pull requests merged in 2022-11, with the labels that each got.

#1081 format JSON response in sample clients
  clients/src/MvcAutomaticTokenManagement/Controllers/HomeController.cs
  clients/src/MvcJarJwt/Controllers/HomeController.cs
  clients/src/MvcJarUriJwt/Controllers/HomeController.cs
Labels: internal

#1091 Update to .NET 7 RTM
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  Directory.Build.targets
  global.json
Labels: enhancement

#1075 add an integration test showing a custom claims service adding an audience claim
  test/IdentityServer.IntegrationTests/Extensibility/CustomClaimsServiceTests.cs
  test/IdentityServer.IntegrationTests/Extensibility/CustomTokenCreationServiceTests.cs
Labels: internal

#1083 Enable TreatWarningsAsErrors
  Directory.Build.props
  test/EntityFramework.Storage.IntegrationTests/Stores/DeviceFlowStoreTests.cs
  test/IdentityServer.UnitTests/Storage/PersistedGrantFilterTests.cs
Labels: internal

#1084 Introduce filter to allow suppression of unhandled exception logs in IdentityServer middleware
  src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs
  src/IdentityServer/Hosting/IdentityServerMiddleware.cs
Labels: enhancement, needs_docs

#1098 Make in memory identity providers not OIDC specific
  src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/IdentityServerBuilderDynamicSchemesExtensions.cs
  src/IdentityServer/Hosting/DynamicProviders/Oidc/IdentityServerBuilderOidcExtensions.cs
  src/IdentityServer/Hosting/DynamicProviders/Store/InMemoryIdentityProviderStore.cs
  test/IdentityServer.IntegrationTests/Hosting/DynamicProvidersTests.cs
Labels: enhancement

#1096 Set the base class AuthenticationSchemeOptions as the restriction
  src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationContext.cs
  src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationOptions.cs
Labels: enhancement
