Repository DuendeSoftware/products, pull requests merged in 2023-04, with the labels that each got.

#1178 Add TokenResponseGenerator.CreateResponseAsync
  src/IdentityServer/ResponseHandling/Default/TokenResponseGenerator.cs
Labels: internal

#1241 Filter authorization codes from token request logs
  src/IdentityServer/Configuration/DependencyInjection/Options/LoggingOptions.cs
Labels: bug

#1243 update UI pages to sync with templates
  hosts/EntityFramework/Pages/Account/Create/Index.cshtml
  hosts/EntityFramework/Pages/Account/Create/Index.cshtml.cs
  hosts/EntityFramework/Pages/Account/Create/InputModel.cs
  hosts/EntityFramework/Pages/Account/Login/Index.cshtml.cs
Labels: internal

#1242 add license validation for dpop
  clients/src/MvcDPoP/Startup.cs
  src/IdentityServer/Validation/Default/License.cs
  src/IdentityServer/Validation/Default/LicenseValidator.cs
  src/IdentityServer/Validation/Default/TokenRequestValidator.cs
  test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
Labels: internal

#1245 Add support for initiate_login_uri
  hosts/Configuration/ClientsWeb.cs
  hosts/EntityFramework/HostingExtensions.cs
  hosts/EntityFramework/Pages/Index.cshtml
  hosts/EntityFramework/Pages/Portal/ClientRepository.cs
  hosts/EntityFramework/Pages/Portal/Index.cshtml
  hosts/EntityFramework/Pages/Portal/Index.cshtml.cs
  hosts/EntityFramework/appsettings.json
  migrations/IdentityServerDb/Migrations/ConfigurationDb.sql
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20230410170353_Configuration.Designer.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20230410170353_Configuration.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/ConfigurationDbContextModelSnapshot.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb.sql
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20230410170347_Grants.Designer.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20230410170347_Grants.cs
  migrations/IdentityServerDb/appsettings.json
  src/EntityFramework.Storage/Entities/Client.cs
  src/EntityFramework.Storage/Extensions/ModelBuilderExtensions.cs
  src/Storage/Models/Client.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/ClientStoreTests.cs
Labels: enhancement, needs_docs

#1249 change dcr license key flag to config_api
  src/IdentityServer/Validation/Default/License.cs
  test/IdentityServer.UnitTests/Validation/LicenseValidatorTests.cs
Labels: internal

#1256 Update to released NuGets of IdentityModel and Access Token Management
  Directory.Build.targets
  clients/src/MvcAutomaticTokenManagement/MvcAutomaticTokenManagement.csproj
  clients/src/MvcDPoP/MvcDPoP.csproj
Labels: internal

#1262 guard against NRE on HttpContext in DefaultEventService
  src/IdentityServer/Services/Default/DefaultEventService.cs
Labels: bug
