Repository DuendeSoftware/products, pull requests merged in 2023-12, with the labels that each got.

#1474 Don't allow pre-release SDKs
  global.json
Labels: internal

#1483 Cleanup build script
  build/Program.cs
Labels: internal

#1488 Make ValidateRefreshTokenAsync virtual
  src/IdentityServer/Services/Default/ServerSideSessionRefreshTokenService.cs
Labels: enhancement

#1486 Fix logout token iss when issuer is missing
  src/IdentityServer/IdentityServerTools.cs
  src/IdentityServer/Services/Default/DefaultBackChannelLogoutService.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultBackChannelLogoutServiceTests.cs
Labels: bug

#1489 Hex encode consent keys
  src/IdentityServer/Stores/Default/DefaultGrantStore.cs
  src/IdentityServer/Stores/Default/DefaultUserConsentStore.cs
  test/IdentityServer.IntegrationTests/Endpoints/Authorize/ConsentTests.cs
Labels: internal

#1490 Brock/merge 6.3.7
  src/IdentityServer/IdentityServerTools.cs
  src/IdentityServer/Services/Default/DefaultBackChannelLogoutService.cs
  src/IdentityServer/Validation/Default/JwtBearerClientAssertionSecretParser.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultBackChannelLogoutServiceTests.cs
Labels: internal

#1493 implement correct overload for IsRedirectUriValidAsync in StrictRedirectUriValidatorAppAuth
  src/IdentityServer/Validation/Default/StrictRedirectUriValidator.cs
  src/IdentityServer/Validation/Default/StrictRedirectUriValidatorAppAuth.cs
  test/IdentityServer.UnitTests/Validation/StrictRedirectUriValidatorAppAuthValidation.cs
Labels: bug

#1492 Remove [Obsolete] from IdentityServerTools
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/IdentityServerTools.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultBackChannelLogoutServiceTests.cs
Labels: internal

#1491 Move tools extension method into tools itself
  src/IdentityServer/Extensions/IEnumerableExtensions.cs
  src/IdentityServer/Extensions/IdentityServerToolsExtensions.cs
  src/IdentityServer/IdentityServerTools.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultBackChannelLogoutServiceTests.cs
Labels: internal

#1494 Include Activity Id in ErrorMessage
  src/IdentityServer/Endpoints/Results/AuthorizeResult.cs
  src/IdentityServer/Events/Infrastructure/Event.cs
  src/IdentityServer/Models/Messages/ErrorMessage.cs
Labels: enhancement

#1498 add copyrights to host files
  hosts/AspNetIdentity/Pages/Telemetry.cs
  hosts/Configuration/Pages/Telemetry.cs
  hosts/EntityFramework/Pages/Telemetry.cs
  hosts/main/Pages/Telemetry.cs
Labels: internal

#1499 more host UI updates to keep the main host and AspId host in sync
  hosts/AspNetIdentity/GlobalSuppressions.cs
  hosts/AspNetIdentity/Pages/Account/Login/Index.cshtml.cs
  hosts/AspNetIdentity/Pages/Account/Login/InputModel.cs
  hosts/AspNetIdentity/Pages/Account/Login/ViewModel.cs
  hosts/AspNetIdentity/Pages/Account/Logout/LogoutOptions.cs
  hosts/AspNetIdentity/Pages/Ciba/All.cshtml
  hosts/AspNetIdentity/Pages/Ciba/All.cshtml.cs
  hosts/AspNetIdentity/Pages/Ciba/Consent.cshtml
  hosts/AspNetIdentity/Pages/Ciba/Consent.cshtml.cs
  hosts/AspNetIdentity/Pages/Ciba/ConsentOptions.cs
  hosts/AspNetIdentity/Pages/Ciba/Index.cshtml
  hosts/AspNetIdentity/Pages/Ciba/Index.cshtml.cs
  hosts/AspNetIdentity/Pages/Ciba/InputModel.cs
  hosts/AspNetIdentity/Pages/Ciba/ViewModel.cs
  hosts/AspNetIdentity/Pages/Ciba/_ScopeListItem.cshtml
  hosts/AspNetIdentity/Pages/Grants/Index.cshtml.cs
  hosts/AspNetIdentity/Pages/IdentityServerSuppressions.cs
  hosts/AspNetIdentity/Pages/Index.cshtml
  hosts/AspNetIdentity/Pages/Index.cshtml.cs
  hosts/AspNetIdentity/Pages/ServerSideSessions/Index.cshtml
  hosts/AspNetIdentity/Pages/ServerSideSessions/Index.cshtml.cs
  hosts/Configuration/GlobalSuppressions.cs
  hosts/Configuration/Pages/IdentityServerSuppressions.cs
  hosts/EntityFramework/GlobalSuppressions.cs
  hosts/EntityFramework/Pages/IdentityServerSuppressions.cs
  hosts/main/GlobalSuppressions.cs
  hosts/main/Pages/Account/Login/Index.cshtml.cs
  hosts/main/Pages/ExternalLogin/Callback.cshtml.cs
  hosts/main/Pages/IdentityServerSuppressions.cs
Labels: internal

#1500 Change some token option defaults
  src/IdentityServer/Services/Default/DefaultIssuerNameService.cs
  src/Storage/Models/Client.cs
Labels: enhancement
