Repository DuendeSoftware/products, pull requests merged in 2023-01, with the labels that each got.

#1117 Improve error logging in serversidesession cleanup
  src/IdentityServer/Hosting/ServerSideSessionCleanupHost.cs
Labels: enhancement

#1114 EmitIssuerIdentificationResponseParameter is reflected in discovery
  src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs
Labels: enhancement

#1097 add exception to UnhandledExceptionEvent
  src/IdentityServer/Events/UnhandledExceptionEvent.cs
Labels: enhancement

#1132 fix bug with resource indicators and not passing offline_access
  .editorconfig
  clients/src/ConsoleResourceIndicators/Program.cs
  src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
  src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs
  src/IdentityServer/Validation/Default/DefaultResourceValidator.cs
  src/IdentityServer/Validation/Default/TokenRequestValidator.cs
  src/IdentityServer/Validation/Models/ResourceValidationRequest.cs
  test/IdentityServer.IntegrationTests/Endpoints/Authorize/ResourceTests.cs
  test/IdentityServer.IntegrationTests/Endpoints/Token/ResourceTests.cs
  test/IdentityServer.UnitTests/Validation/ResourceValidation.cs
Labels: bug

#1118 Fixes ToOptimizedRawValues to handle multiple resource values when combined with resource indicators
  src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs
  src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationContext.cs
  src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationOptions.cs
  src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/IdentityServerBuilderDynamicSchemesExtensions.cs
  src/IdentityServer/Hosting/DynamicProviders/Oidc/IdentityServerBuilderOidcExtensions.cs
  src/IdentityServer/Hosting/DynamicProviders/Store/InMemoryIdentityProviderStore.cs
  test/IdentityServer.IntegrationTests/Hosting/DynamicProvidersTests.cs
  test/IdentityServer.UnitTests/Extensions/ValidatedAuthorizeRequestExtensionsTests.cs
Labels: bug

#1140 Fixes ToOptimizedRawValues to handle multiple resource values when combined with resource indicators
  src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs
  test/IdentityServer.UnitTests/Extensions/ValidatedAuthorizeRequestExtensionsTests.cs
Labels: bug

#1141 When cookie is re-issued ensure the issuer is captured in the ticket
  src/IdentityServer/Services/Default/DefaultSessionCoordinationService.cs
  src/IdentityServer/Stores/Default/ServerSideTicketStore.cs
Labels: bug

#1105 Refresh Token Consumption Rework
  src/EntityFramework.Storage/Options/OperationalStoreOptions.cs
  src/EntityFramework.Storage/TokenCleanup/TokenCleanupService.cs
  src/IdentityServer/Services/Default/DefaultRefreshTokenService.cs
  src/Storage/Stores/Serialization/PersistentGrantSerializer.cs
  test/EntityFramework.Storage.IntegrationTests/TokenCleanup/TokenCleanupTests.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultRefreshTokenServiceTests.cs
  test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Labels: enhancement

#1146 handle formatted back-channel logout error messages
  src/IdentityServer/Services/Default/BackChannelLogoutHttpClient.cs
  test/IdentityServer.IntegrationTests/Endpoints/EndSession/EndSessionTests.cs
Labels: enhancement

#1145 Update audience logic for private key JWT client authN
  src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs
  test/IdentityServer.UnitTests/Validation/Secrets/PrivateKeyJwtSecretValidation.cs
Labels: enhancement

#1149 Make constants for EndpointNames public
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/Constants.cs
  src/IdentityServer/Endpoints/AuthorizeCallbackEndpoint.cs
  src/IdentityServer/Endpoints/AuthorizeEndpoint.cs
  src/IdentityServer/Endpoints/BackchannelAuthenticationEndpoint.cs
  src/IdentityServer/Endpoints/CheckSessionEndpoint.cs
  src/IdentityServer/Endpoints/DeviceAuthorizationEndpoint.cs
  src/IdentityServer/Endpoints/DiscoveryEndpoint.cs
  src/IdentityServer/Endpoints/DiscoveryKeyEndpoint.cs
  src/IdentityServer/Endpoints/EndSessionCallbackEndpoint.cs
  src/IdentityServer/Endpoints/EndSessionEndpoint.cs
  src/IdentityServer/Endpoints/IntrospectionEndpoint.cs
  src/IdentityServer/Endpoints/TokenEndpoint.cs
  src/IdentityServer/Endpoints/TokenRevocationEndpoint.cs
  src/IdentityServer/Endpoints/UserInfoEndpoint.cs
  src/IdentityServer/Events/BackchannelAuthenticationFailureEvent.cs
  src/IdentityServer/Events/BackchannelAuthenticationSuccessEvent.cs
  src/IdentityServer/Events/DeviceAuthorizationFailureEvent.cs
  src/IdentityServer/Events/DeviceAuthorizationSuccessEvent.cs
  src/IdentityServer/Events/TokenIssuedFailureEvent.cs
  src/IdentityServer/Events/TokenIssuedSuccessEvent.cs
  src/IdentityServer/Events/UserLoginFailureEvent.cs
  src/IdentityServer/Events/UserLoginSuccessEvent.cs
  src/IdentityServer/Extensions/EndpointOptionsExtensions.cs
  src/IdentityServer/IdentityServerConstants.cs
  test/IdentityServer.UnitTests/Extensions/EndpointOptionsExtensionsTests.cs
  test/IdentityServer.UnitTests/Hosting/EndpointRouterTests.cs
Labels: enhancement

#1150 add new API to IRedirectUriValidator with more request context
  src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
  src/IdentityServer/Validation/IRedirectUriValidator.cs
Labels: enhancement, needs_docs

#1151 improved error logs
  src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
  src/IdentityServer/Validation/Default/LicenseValidator.cs
Labels: enhancement

#1152 Update IdentityModel
  Directory.Build.targets
Labels: internal
