Repository DuendeSoftware/products, pull requests merged in 2023-07, with the labels that each got.

#1356 Merge 6.2.x patch into 6.3.x
  src/IdentityServer/Services/Default/DefaultUserSession.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultUserSessionTests.cs
Labels: bug

#1350 Clients: remove old IdentityModel OIDC helper and update to .net8
  clients/src/APIs/DPoPApi/DPoP/DPoPJwtBearerEvents.cs
  clients/src/APIs/DPoPApi/DPoPApi.csproj
  clients/src/APIs/ResourceBasedApi/ResourceBasedApi.csproj
  clients/src/APIs/SimpleApi/SimpleApi.csproj
  clients/src/ConsoleCibaClient/ConsoleCibaClient.csproj
  clients/src/ConsoleClientCredentialsFlow/ConsoleClientCredentialsFlow.csproj
  clients/src/ConsoleClientCredentialsFlowCallingIdentityServerApi/ConsoleClientCredentialsFlowCallingIdentityServerApi.csproj
  clients/src/ConsoleClientCredentialsFlowDPoP/ConsoleClientCredentialsFlowDPoP.csproj
  clients/src/ConsoleClientCredentialsFlowPostBody/ConsoleClientCredentialsFlowPostBody.csproj
  clients/src/ConsoleCode/ConsoleCode.csproj
  clients/src/ConsoleCustomGrant/ConsoleExtensionGrant.csproj
  clients/src/ConsoleDcrClient/ConsoleDcrClient.csproj
  clients/src/ConsoleDeviceFlow/ConsoleDeviceFlow.csproj
  clients/src/ConsoleEphemeralMtlsClient/ConsoleEphemeralMtlsClient.csproj
  clients/src/ConsoleIntrospectionClient/ConsoleIntrospectionClient.csproj
  clients/src/ConsoleMTLSClient/ConsoleMTLSClient.csproj
  clients/src/ConsoleParameterizedScopeClient/ConsoleParameterizedScopeClient.csproj
  clients/src/ConsolePrivateKeyJwtClient/ConsolePrivateKeyJwtClient.csproj
  clients/src/ConsoleResourceIndicators/ConsoleResourceIndicators.csproj
  clients/src/ConsoleResourceOwnerFlow/ConsoleResourceOwnerFlow.csproj
  clients/src/ConsoleResourceOwnerFlowPublic/ConsoleResourceOwnerFlowPublic.csproj
  clients/src/ConsoleResourceOwnerFlowReference/ConsoleResourceOwnerFlowReference.csproj
  clients/src/ConsoleResourceOwnerFlowRefreshToken/ConsoleResourceOwnerFlowRefreshToken.csproj
  clients/src/ConsoleResourceOwnerFlowUserInfo/ConsoleResourceOwnerFlowUserInfo.csproj
  clients/src/ConsoleScopesResources/ConsoleScopesResources.csproj
  clients/src/JsOidc/JsOidc.csproj
  clients/src/MvcAutomaticTokenManagement/MvcAutomaticTokenManagement.csproj
  clients/src/MvcCode/MvcCode.csproj
  clients/src/MvcDPoP/MvcDPoP.csproj
  clients/src/MvcHybridBackChannel/Controllers/LogoutController.cs
  clients/src/MvcHybridBackChannel/MvcHybridBackChannel.csproj
  clients/src/MvcJarJwt/AssertionConfigurationService.cs
  clients/src/MvcJarJwt/ClientAssertionService.cs
  clients/src/MvcJarJwt/MvcJarJwt.csproj
  clients/src/MvcJarJwt/Startup.cs
  clients/src/MvcJarUriJwt/AssertionConfigurationService.cs
  clients/src/MvcJarUriJwt/ClientAssertionService.cs
  clients/src/MvcJarUriJwt/MvcJarUriJwt.csproj
  clients/src/MvcJarUriJwt/Startup.cs
Labels: internal

#1334 add support for introspection for refresh tokens
  src/IdentityServer/Endpoints/IntrospectionEndpoint.cs
  src/IdentityServer/Events/TokenIntrospectionSuccessEvent.cs
  src/IdentityServer/Extensions/DateTimeExtensions.cs
  src/IdentityServer/ResponseHandling/Default/IntrospectionResponseGenerator.cs
  src/IdentityServer/Validation/Contexts/IntrospectionRequestValidationContext.cs
  src/IdentityServer/Validation/Default/IntrospectionRequestValidator.cs
  src/IdentityServer/Validation/IIntrospectionRequestValidator.cs
  src/IdentityServer/Validation/Models/IntrospectionRequestValidationResult.cs
  test/IdentityServer.IntegrationTests/Endpoints/Introspection/IntrospectionTests.cs
  test/IdentityServer.IntegrationTests/Endpoints/Introspection/Setup/Clients.cs
  test/IdentityServer.UnitTests/Validation/IntrospectionRequestValidatorTests.cs
  test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Labels: enhancement, needs_docs, breaking_change

#1320 remove unnecessary call to ToModel in device flow
  src/EntityFramework.Storage/Stores/DeviceFlowStore.cs
  src/IdentityServer/Hosting/IdentityServerMiddleware.cs
Labels: internal

#1321 use session id when revoking reference tokens for refresh token
  src/IdentityServer/ResponseHandling/Default/TokenRevocationResponseGenerator.cs
  src/IdentityServer/Stores/Default/DefaultGrantStore.cs
  src/IdentityServer/Stores/Default/DefaultReferenceTokenStore.cs
  src/Storage/Stores/IReferenceTokenStore.cs
  test/IdentityServer.IntegrationTests/Endpoints/Revocation/RevocationTests.cs
  test/IdentityServer.UnitTests/Common/MockReferenceTokenStore.cs
Labels: bug, needs_docs, breaking_change

#1331 return error for unknown prompt values on authorize endpoint
  src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
  test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
Labels: bug, breaking_change

#1363 Remove raw exception from unhandled exception event
  src/IdentityServer/Events/UnhandledExceptionEvent.cs
  test/IdentityServer.UnitTests/Events/EventTests.cs
Labels: bug, breaking_change

#1367 Minor DCR xmldoc fixes
  src/Configuration/Models/DynamicClientRegistration/DynamicClientRegistrationRequest.cs
  src/Configuration/Validation/DynamicClientRegistration/DynamicClientRegistrationValidator.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/KeyManagementOptions.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/ValidationOptions.cs
  src/IdentityServer/ResponseHandling/Default/TokenResponseGenerator.cs
  src/IdentityServer/ResponseHandling/Models/TokenResponse.cs
  src/IdentityServer/Services/Default/DefaultUserSession.cs
  src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs
Labels: internal

#1338 Add DPoP support to our AddLocalApi access token validation
  clients/src/APIs/DPoPApi/DPoP/DPoPProofValidator.cs
  src/IdentityServer/Hosting/LocalApiAuthentication/LocalApiAuthenticationHandler.cs
  src/IdentityServer/Hosting/LocalApiAuthentication/LocalApiAuthenticationOptions.cs
  src/IdentityServer/Hosting/LocalApiAuthentication/LocalApiTokenMode.cs
  src/IdentityServer/Validation/Contexts/DPoPProofValidatonContext.cs
  src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs
  src/IdentityServer/Validation/Default/TokenRequestValidator.cs
  src/IdentityServer/Validation/Models/DPoPProofValidatonResult.cs
  test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs
  test/IdentityServer.IntegrationTests/Hosting/LocalApiAuthentication/LocalApiAuthenticationTests.cs
  test/IdentityServer.UnitTests/Validation/DPoPProofValidatorTests.cs
  test/IdentityServer.UnitTests/Validation/Setup/Factory.cs
Labels: enhancement, needs_docs, breaking_change

#1370 Merge 6.3.4 patch to main
  src/IdentityServer/Services/Default/OidcReturnUrlParser.cs
  src/IdentityServer/Services/IReturnUrlParser.cs
Labels: internal

#1327 When using server-side sessions, load subject from server side session store if in use
  Duende.IdentityServer.Clients.sln
  Duende.IdentityServer.Core.sln
  src/IdentityServer/Validation/Default/UserInfoRequestValidator.cs
Labels: enhancement

#1377 Map entities to/from models by hand
  .vscode/launch.json
  .vscode/tasks.json
  Directory.Build.targets
  clients/src/APIs/SimpleApi/Program.cs
  hosts/EntityFramework/Extensions/ParameterizedScopeParser.cs
  hosts/EntityFramework/IdentityServerExtensions.cs
  hosts/EntityFramework/appsettings.json
  src/EntityFramework.Storage/Duende.IdentityServer.EntityFramework.Storage.csproj
  src/EntityFramework.Storage/Mappers/AllowedSigningAlgorithmsConverter.cs
  src/EntityFramework.Storage/Mappers/ApiResourceMapperProfile.cs
  src/EntityFramework.Storage/Mappers/ApiResourceMappers.cs
  src/EntityFramework.Storage/Mappers/ClientMapperProfile.cs
  src/EntityFramework.Storage/Mappers/ClientMappers.cs
  src/EntityFramework.Storage/Mappers/IdentityProviderMapperProfile.cs
  src/EntityFramework.Storage/Mappers/IdentityProviderMappers.cs
  src/EntityFramework.Storage/Mappers/IdentityResourceMapperProfile.cs
  src/EntityFramework.Storage/Mappers/IdentityResourceMappers.cs
  src/EntityFramework.Storage/Mappers/PersistedGrantMapperProfile.cs
  src/EntityFramework.Storage/Mappers/PersistedGrantMappers.cs
  src/EntityFramework.Storage/Mappers/PropertiesConverter.cs
  src/EntityFramework.Storage/Mappers/ScopeMapperProfile.cs
  src/EntityFramework.Storage/Mappers/ScopeMappers.cs
  src/Storage/Models/IdentityProvider.cs
  test/EntityFramework.Storage.UnitTests/Mappers/ApiResourceMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/ClientMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/IdentityProviderMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/IdentityResourcesMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/MapperTestHelpers.cs
  test/EntityFramework.Storage.UnitTests/Mappers/PersistedGrantMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/ScopeMappersTests.cs
Labels: internal
