Repository DuendeSoftware/products, pull requests merged in 2023-09, with the labels that each got.

#1265 Add post configuration of identity server options
  src/AspNetIdentity/IdentityServerBuilderExtensions.cs
  src/AspNetIdentity/PostConfigureIdentityServerOptions.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/DynamicProviderOptions.cs
Labels: enhancement

#1403 Joe/refresh token thumprints
  .vscode/launch.json
  .vscode/tasks.json
  src/IdentityServer/Extensions/TokenExtensions.cs
  test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs
  test/IdentityServer.UnitTests/Extensions/TokenExtensionsTests.cs
Labels: bug

#1412 Merge Releases/6.3.4 patch into main
  .vscode/launch.json
  .vscode/tasks.json
  src/IdentityServer/Extensions/TokenExtensions.cs
  test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs
  test/IdentityServer.UnitTests/Extensions/TokenExtensionsTests.cs
Labels: internal

#1414 Fix optional license dependency
  hosts/main/Pages/Index.cshtml.cs
Labels: internal

#1418 Upgrade FluentAssertions from 5.10.1 to 6.5.1
  Directory.Build.targets
  test/EntityFramework.Storage.IntegrationTests/Stores/DeviceFlowStoreTests.cs
  test/IdentityServer.IntegrationTests/Endpoints/Authorize/AuthorizeTests.cs
  test/IdentityServer.IntegrationTests/TestFramework/GenericHost.cs
  test/IdentityServer.IntegrationTests/TestFramework/TestBrowserClient.cs
  test/IdentityServer.UnitTests/Extensions/IResourceStoreExtensionsTests.cs
  test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests_Consent.cs
  test/IdentityServer.UnitTests/ResponseHandling/DeviceAuthorizationResponseGeneratorTests.cs
  test/IdentityServer.UnitTests/ResponseHandling/UserInfoResponseGeneratorTests.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultBackchannelAuthenticationInteractionServiceTests.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultIdentityServerInteractionServiceTests.cs
  test/IdentityServer.UnitTests/Services/Default/DistributedDeviceFlowThrottlingServiceTests.cs
  test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Invalid.cs
  test/IdentityServer.UnitTests/Validation/DeviceAuthorizationRequestValidation.cs
  test/IdentityServer.UnitTests/Validation/Secrets/MutualTlsSecretValidation.cs
  test/IdentityServer.UnitTests/Validation/TokenRequest Validation/TokenRequestValidation_General_Invalid.cs
Labels: internal

#1422 Joe/6.3 bugfix/error event serialization
  src/IdentityServer/Events/UnhandledExceptionEvent.cs
  test/IdentityServer.UnitTests/Events/EventTests.cs
Labels: bug
