Repository DuendeSoftware/products, pull requests merged in 2023-11, with the labels that each got.

#1453 Expose suppressed and original prompt modes
  src/IdentityServer/Constants.cs
  src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs
  src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs
  src/IdentityServer/Validation/Models/ValidatedAuthorizeRequest.cs
  test/IdentityServer.UnitTests/ResponseHandling/AuthorizeInteractionResponseGenerator/AuthorizeInteractionResponseGeneratorTests_Login.cs
  test/IdentityServer.UnitTests/Validation/AuthorizeRequest Validation/Authorize_ProtocolValidation_Valid.cs
Labels: breaking_change

#1462 Discourage IAuthorizationParametersMessageStore
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
  src/IdentityServer/Endpoints/Results/AuthorizeInteractionPageResult.cs
  src/IdentityServer/Extensions/ValidatedAuthorizeRequestExtensions.cs
  test/IdentityServer.UnitTests/Extensions/ValidatedAuthorizeRequestExtensionsTests.cs
Labels: internal

#1464 Ease extension of DCR classes with protected props
  src/Configuration/RequestProcessing/DynamicClientRegistrationRequestProcessor.cs
  src/Configuration/ResponseGeneration/DynamicClientRegistrationResponseGenerator.cs
  src/Configuration/Validation/DynamicClientRegistration/DynamicClientRegistrationValidator.cs
  src/Configuration/Validation/DynamicClientRegistration/IDynamicClientRegistrationValidationResult.cs
Labels: enhancement

#1463 Change ServerSideSession.Id to long
  migrations/IdentityServerDb/Migrations/ConfigurationDb.sql
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20231110071401_Configuration.Designer.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20231110071401_Configuration.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/ConfigurationDbContextModelSnapshot.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb.sql
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20231110071347_Grants.Designer.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20231110071347_Grants.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/PersistedGrantDbContextModelSnapshot.cs
  src/EntityFramework.Storage/Entities/ServerSideSession.cs
Labels: schema change, needs_docs, breaking_change

#1454 Provide abstraction for IdentityServerTools
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/Extensions/IdentityServerToolsExtensions.cs
  src/IdentityServer/IdentityServerTools.cs
  src/IdentityServer/Services/Default/DefaultBackChannelLogoutService.cs
  test/IdentityServer.IntegrationTests/Endpoints/Ciba/CibaTests.cs
Labels: enhancement, needs_docs, breaking_change
