Repository DuendeSoftware/products, pull requests merged in 2023-02, with the labels that each got.

#1154 fix non-unique names in endpoint list and add health check sample
  hosts/main/DiscoveryHealthCheck.cs
  hosts/main/HostingExtensions.cs
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/IdentityServerConstants.cs
Labels: bug

#1155 Launch and tasks files for vscode
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
Labels: internal

#1170 add LogoutTokenJwtType property for back channel logout tokens
  src/IdentityServer/Configuration/DependencyInjection/Options/IdentityServerOptions.cs
  src/IdentityServer/IdentityServerConstants.cs
  src/IdentityServer/IdentityServerTools.cs
  src/IdentityServer/Services/Default/DefaultBackChannelLogoutService.cs
  src/IdentityServer/Services/Default/DefaultTokenCreationService.cs
  test/IdentityServer.IntegrationTests/Endpoints/EndSession/EndSessionTests.cs
Labels: bug, needs_docs

#1172 requests to ~/federation with no additional segments should return not found
  src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs
  test/IdentityServer.IntegrationTests/Hosting/DynamicProvidersTests.cs
Labels: bug

#1174 enhance InputLengthRestrictions checking on the BasicAuthenticationSecretParser
  src/IdentityServer/Validation/Default/BasicAuthenticationSecretParser.cs
  test/IdentityServer.UnitTests/Validation/Secrets/BasicAuthenticationCredentialParsing.cs
Labels: enhancement
