Repository DuendeSoftware/products, pull requests merged in 2023-03, with the labels that each got.

#1208 Add whitespace to logs from TokenRequestValidator
  src/IdentityServer/Validation/Default/TokenRequestValidator.cs
Labels: bug

#1214 Expose CSP hashes as constants
  src/IdentityServer/Endpoints/Results/AuthorizeResult.cs
  src/IdentityServer/Endpoints/Results/CheckSessionResult.cs
  src/IdentityServer/Endpoints/Results/EndSessionCallbackResult.cs
  src/IdentityServer/IdentityServerConstants.cs
  test/IdentityServer.UnitTests/Endpoints/Results/AuthorizeResultTests.cs
  test/IdentityServer.UnitTests/Endpoints/Results/CheckSessionResultTests.cs
Labels: enhancement

#1217 Make ProtocolRoutePaths constants public
  src/IdentityServer/Configuration/DependencyInjection/Options/CorsOptions.cs
  src/IdentityServer/Constants.cs
  src/IdentityServer/Endpoints/Results/AuthorizeInteractionPageResult.cs
  src/IdentityServer/Extensions/HttpContextExtensions.cs
  src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs
  src/IdentityServer/IdentityServerConstants.cs
  src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs
  src/IdentityServer/Services/Default/OidcReturnUrlParser.cs
  src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs
  src/IdentityServer/Validation/Default/PrivateKeyJwtSecretValidator.cs
Labels: enhancement

#1213 small DPoP proof cleanup
  src/IdentityServer/ResponseHandling/Default/TokenResponseGenerator.cs
  src/IdentityServer/Validation/Default/TokenRequestValidator.cs
Labels: internal

#1215 Add ITokenCleanupService Interface
  src/EntityFramework.Storage/Configuration/ServiceCollectionExtensions.cs
  src/EntityFramework.Storage/TokenCleanup/ITokenCleanupService.cs
  src/EntityFramework.Storage/TokenCleanup/TokenCleanupService.cs
  src/EntityFramework/TokenCleanupHost.cs
  test/EntityFramework.Storage.IntegrationTests/TokenCleanup/TokenCleanupTests.cs
Labels: bug, enhancement

#1219 Send custom logout reason value in back channel logout notification token
  src/IdentityServer/IdentityServerConstants.cs
  src/IdentityServer/Models/Contexts/LogoutNotificationContext.cs
  src/IdentityServer/Models/Contexts/LogoutNotificationReason.cs
  src/IdentityServer/Services/Default/DefaultBackChannelLogoutService.cs
  src/IdentityServer/Services/Default/DefaultSessionCoordinationService.cs
  src/IdentityServer/Services/Default/DefaultSessionManagementService.cs
  src/IdentityServer/Services/Default/LogoutNotificationService.cs
  src/IdentityServer/Services/ILogoutNotificationService.cs
  test/IdentityServer.IntegrationTests/Endpoints/EndSession/EndSessionTests.cs
Labels: enhancement

#1223 update dpop client and api sample
  clients/src/APIs/DPoPApi/DPoPJwtBearerEvents.cs
  clients/src/APIs/DPoPApi/IdentityController.cs
  clients/src/APIs/DPoPApi/Startup.cs
  clients/src/MvcDPoP/CustomProofService.cs
  clients/src/MvcDPoP/DPoPOpenIdConnectEvents.cs
  clients/src/MvcDPoP/DPoPProofApiMessageHandler.cs
  clients/src/MvcDPoP/DPoPProofHelpers.cs
  clients/src/MvcDPoP/DPoPProofTokenEndpointMessageHandler.cs
  clients/src/MvcDPoP/DPoPUserTokenEndpointService.cs
  clients/src/MvcDPoP/MvcDPoP.csproj
  clients/src/MvcDPoP/Program.cs
  clients/src/MvcDPoP/Startup.cs
  clients/src/MvcDPoP/TestHandler.cs
Labels: internal

#1227 updated code comments for DPoP
  src/IdentityServer/Configuration/DependencyInjection/Options/DPoPOptions.cs
  src/IdentityServer/Validation/Models/DPoPProofValidatonResult.cs
  src/Storage/Models/Client.cs
Labels: internal

#1225 attempt to simplify the dpop proof token expiration logic
  clients/src/APIs/DPoPApi/DPoPJwtBearerEvents.cs
  src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs
  test/IdentityServer.UnitTests/Validation/DPoPProofValidatorTests.cs
Labels: internal

#1229 Fix dpop_signing_alg_values_supported
  src/IdentityServer/ResponseHandling/Default/DiscoveryResponseGenerator.cs
Labels: bug

#1228 Fix dpop jwt type
  clients/src/APIs/DPoPApi/DPoPJwtBearerEvents.cs
  src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs
  test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs
  test/IdentityServer.UnitTests/Validation/DPoPProofValidatorTests.cs
Labels: bug

#1232 improve the DPoP token handling support for the sample API
  clients/src/APIs/DPoPApi/DPoP/ConfigureJwtBearerOptions.cs
  clients/src/APIs/DPoPApi/DPoP/DPoPExtensions.cs
  clients/src/APIs/DPoPApi/DPoP/DPoPJwtBearerEvents.cs
  clients/src/APIs/DPoPApi/DPoP/DPoPMode.cs
  clients/src/APIs/DPoPApi/DPoP/DPoPOptions.cs
  clients/src/APIs/DPoPApi/DPoP/DPoPProofValidatonContext.cs
  clients/src/APIs/DPoPApi/DPoP/DPoPProofValidatonResult.cs
  clients/src/APIs/DPoPApi/DPoP/DPoPProofValidator.cs
  clients/src/APIs/DPoPApi/DPoP/DPoPServiceCollectionExtensions.cs
  clients/src/APIs/DPoPApi/DPoP/IReplayCache.cs
  clients/src/APIs/DPoPApi/DPoP/JsonWebKeyExtensions.cs
  clients/src/APIs/DPoPApi/DPoP/RequireCnfJwtBearerEvents.cs
  clients/src/APIs/DPoPApi/IdentityController.cs
  clients/src/APIs/DPoPApi/Startup.cs
  clients/src/MvcDPoP/TestHandler.cs
Labels: internal

#1233 add some extra logging to dpop validation
  src/IdentityServer/Validation/Default/DefaultDPoPProofValidator.cs
  test/IdentityServer.IntegrationTests/Endpoints/Token/DPoPTokenEndpointTests.cs
Labels: internal
