Repository DuendeSoftware/products, pull requests merged in 2024-01, with the labels that each got.

#1497 CIBA Customization Extensibility Points
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Additional.cs
  src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs
  src/IdentityServer/Endpoints/Results/BackchannelAuthenticationResult.cs
  src/IdentityServer/Models/BackchannelUserLoginRequest.cs
  src/IdentityServer/ResponseHandling/Default/BackchannelAuthenticationResponseGenerator.cs
  src/IdentityServer/ResponseHandling/Models/BackchannelAuthenticationResponse.cs
  src/IdentityServer/Services/Default/DefaultBackchannelAuthenticationInteractionService.cs
  src/IdentityServer/Validation/Contexts/CustomBackchannelAuthenticationRequestValidationContext.cs
  src/IdentityServer/Validation/Default/BackchannelAuthenticationRequestValidator.cs
  src/IdentityServer/Validation/Default/DefaultCustomBackchannelAuthenticationValidator.cs
  src/IdentityServer/Validation/ICustomBackchannelAuthenticationValidator.cs
  src/IdentityServer/Validation/Models/ValidatedBackchannelAuthenticationRequest.cs
  src/Storage/Models/BackChannelAuthenticationRequest.cs
  test/IdentityServer.IntegrationTests/Common/MockCustomBackchannelAuthenticationValidator.cs
  test/IdentityServer.IntegrationTests/Endpoints/Ciba/CibaTests.cs
Labels: enhancement

#1501 Use ExecuteDelete in token cleanup
  Duende.IdentityServer.sln
  migrations/IdentityServerDb/Migrations/ConfigurationDb.sql
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20240104192404_Configuration.Designer.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/20240104192404_Configuration.cs
  migrations/IdentityServerDb/Migrations/ConfigurationDb/ConfigurationDbContextModelSnapshot.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb.sql
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20240104192353_Grants.Designer.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/20240104192353_Grants.cs
  migrations/IdentityServerDb/Migrations/PersistedGrantDb/PersistedGrantDbContextModelSnapshot.cs
  src/EntityFramework.Storage/DbContexts/PersistedGrantDbContext.cs
  src/EntityFramework.Storage/Extensions/ModelBuilderExtensions.cs
  src/EntityFramework.Storage/Options/OperationalStoreOptions.cs
  src/EntityFramework.Storage/TokenCleanup/TokenCleanupService.cs
  src/EntityFramework/TokenCleanupHost.cs
  src/IdentityServer/Configuration/DependencyInjection/Options/ServerSideSessionOptions.cs
  src/IdentityServer/Hosting/ServerSideSessionCleanupHost.cs
  test/EntityFramework.IntegrationTests/DI/DITests.cs
  test/EntityFramework.IntegrationTests/DatabaseProviderBuilder.cs
  test/EntityFramework.IntegrationTests/DatabaseProviderFixture.cs
  test/EntityFramework.IntegrationTests/EntityFramework.IntegrationTests.csproj
  test/EntityFramework.IntegrationTests/FakeLogger.cs
  test/EntityFramework.IntegrationTests/IntegrationTest.cs
  test/EntityFramework.IntegrationTests/Services/CorsPolicyServiceTests.cs
  test/EntityFramework.Storage.IntegrationTests/DatabaseProviderBuilder.cs
  test/EntityFramework.Storage.IntegrationTests/DatabaseProviderFixture.cs
  test/EntityFramework.Storage.IntegrationTests/DbContexts/ClientDbContextTests.cs
  test/EntityFramework.Storage.IntegrationTests/FakeLogger.cs
  test/EntityFramework.Storage.IntegrationTests/IntegrationTest.cs
  test/EntityFramework.Storage.IntegrationTests/MockOperationalStoreNotification.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/ClientStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/DeviceFlowStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/IdentityProviderStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/PersistedGrantStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/Stores/ResourceStoreTests.cs
  test/EntityFramework.Storage.IntegrationTests/TokenCleanup/TokenCleanupTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/ApiResourceMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/ClientMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/IdentityProviderMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/IdentityResourcesMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/PersistedGrantMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/PushedAuthorizationRequestMappersTests.cs
  test/EntityFramework.Storage.UnitTests/Mappers/ScopeMappersTests.cs
Labels: schema change, needs_docs

#1508 Expanded xmldoc for Client.PollingInterval
  src/Storage/Models/Client.cs
Labels: no release notes needed

#1506 Return successfully deserialized grants even if some fail
  src/IdentityServer/Services/Default/DefaultPersistedGrantService.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultPersistedGrantServiceTests.cs
Labels: enhancement

#1509 Merge 6.3.8 into main
  src/IdentityServer/Services/Default/DefaultPersistedGrantService.cs
  test/IdentityServer.UnitTests/Services/Default/DefaultPersistedGrantServiceTests.cs
Labels: internal

#1512 Do not auto-include custom ciba request params in response
  src/IdentityServer/Endpoints/Results/BackchannelAuthenticationResult.cs
  src/IdentityServer/Models/BackchannelUserLoginRequest.cs
  src/IdentityServer/ResponseHandling/Default/BackchannelAuthenticationResponseGenerator.cs
  src/IdentityServer/ResponseHandling/Models/BackchannelAuthenticationResponse.cs
  src/IdentityServer/Validation/Models/ValidatedBackchannelAuthenticationRequest.cs
  src/Storage/Models/BackChannelAuthenticationRequest.cs
  test/IdentityServer.IntegrationTests/Endpoints/Ciba/CibaTests.cs
Labels: internal
